cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'coreutils'
brew 'wget', args: ['enable-iri']
brew 'findutils'
brew 'thefuck'
brew 'bash'
brew 'ack'
brew 'git'
brew 'tree'
brew 'htop-osx'
brew 'hub'
brew 'git-extras'
brew 'autojump'
brew 'curl'
brew 'awk'
brew 'php56', args: ['with-gmp', 'with-apache', 'homebrew-apxs']
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'keybase'
brew 'watch'
brew 'httpie'
brew 'diff-so-fancy'
brew 'jq'
brew 'go'
brew 'openssl'
brew 'youtube-dl'
brew 'yarn'
brew 'zplug'
brew 'gpg'

cask 'alfred'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'safari-technology-preview'
cask 'firefox'
cask 'firefoxdeveloperedition'
cask 'iterm2'
cask 'the-unarchiver'
cask 'transmission'
cask 'virtualbox'
cask 'atom'
cask 'atom-beta'
cask 'vlc'
cask 'spectacle'
cask 'tunnelbear'
cask 'slack'
cask 'spotify'
cask 'appearin'
